server:
  port: 8082
spring:
  application:
    name: quartz-test
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: DefaultQuartzScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            dataSource: default
            acquireTriggersWithinLock: true # 多实例加锁
            clusterCheckinInterval: 10000
            useProperties: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

          dataSource:
            default:
              URL: jdbc:mysql://localhost:3306/quartz_test_68?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&allowMultiQueries=true&nullCatalogMeansCurrent=true
              user: root
              password: 123456
              driver: com.mysql.cj.jdbc.Driver
              maxConnections: 10
#  datasource:
#    url: jdbc:mysql://localhost:3306/quartz-test?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&allowMultiQueries=true&nullCatalogMeansCurrent=true
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
